### ISSUE TITLE
你好，请问还有这个proj的源代码吗

### ISSUE THREAD

**Issue by EnochDogu** [PKUFlyingPig/CS186#1]
官网好像找不到proj1后面的代码了

**Comment by EnochDogu** [comment]
不好意思，好像知道怎么弄了

**Comment by trace1729** [comment]
请问是怎么解决的呀，利用git回滚吗

**Comment by EnochDogu** [comment]
> 
最近有点忙，自己没有在学了。我看文档里说有好几个branch，不知道那些是不是就是源码呢。
https://github.com/PKUFlyingPig/CS186-Rookiedb
